// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChW6k2uY6FI69KiLYDltQecJqAqyFnhKs',
    appId: '1:746759675129:web:c9ad8c4dada68cab179628',
    messagingSenderId: '746759675129',
    projectId: 'insta2023-e6bb8',
    authDomain: 'insta2023-e6bb8.firebaseapp.com',
    storageBucket: 'insta2023-e6bb8.appspot.com',
    measurementId: 'G-4W8SHSES7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjCRfpo3YWD_oJtCbCkTEbol3dAJCKKZ4',
    appId: '1:746759675129:android:bde3a8bae359c923179628',
    messagingSenderId: '746759675129',
    projectId: 'insta2023-e6bb8',
    storageBucket: 'insta2023-e6bb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbNxafNnbDRY8qM90FAy75usDbz8aCVWs',
    appId: '1:746759675129:ios:67e960af893326be179628',
    messagingSenderId: '746759675129',
    projectId: 'insta2023-e6bb8',
    storageBucket: 'insta2023-e6bb8.appspot.com',
    iosClientId: '746759675129-o8o4ul0bafun47e3igiklmf6no2sti0l.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbNxafNnbDRY8qM90FAy75usDbz8aCVWs',
    appId: '1:746759675129:ios:67e960af893326be179628',
    messagingSenderId: '746759675129',
    projectId: 'insta2023-e6bb8',
    storageBucket: 'insta2023-e6bb8.appspot.com',
    iosClientId: '746759675129-o8o4ul0bafun47e3igiklmf6no2sti0l.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );
}
